--- #YAML:1.0
name:               JavaScript-Runtime-OpcodeCounting
version:            1.02
abstract:           JavaScript::Runtime that counts how many opcodes that are executed
author:
    - Claes Jakobsson <claesjac@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JavaScript:  1.03
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
